#start service configure
server:
  port: 5678

#wecheat configure
wx:oWoxv5zCn54YSdUMr1fctPVpsAm4
  app-id:wx2e650cc251405cad
  app-secret:0c854ee5724d4be1816de6e6fe9714d6
  app-get-access-token: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential
  app-send-msg: https://api.weixin.qq.com/cgi-bin/message/template/send?access_token=
  #hito
  app-yy-tips: https://v1.hitokoto.cn/?c=j
  #baidu天气接口ack
  app_baidu_ack:	3e52eefcec6c448ea782275fb63ef293

#mysql configure
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/partnerpush?userUnicode=true&characterEncoding=UTF8&useSSL=false
 env:
      APP_ID: ${{ secrets.APP_ID }}
      APP_SECRET: ${{ secrets.APP_SECRET }}
      TEMPLATE_ID: ${{ secrets.TEMPLATE_ID }}
      USER_ID: ${{ secrets.USER_ID }}
      START_DATE: ${{ secrets.START_DATE }}
      BIRTHDAY: ${{ secrets.BIRTHDAY }}
      CITY: ${{ secrets.CITY }}
